clone:
  CLONE REPO:
    image: plugins/git
    depth: 1

pipeline:
  INSTALL DEPENDENCIES:
    image: node:8.10
    commands:
      - npm install

  LINT:
    image: node:8.10
    commands:
      - npm run lint

  UNIT TEST:
    image: node:8.10
    commands:
      - npm run test

  NPM TOKEN:
    image: node:8.10
    commands:
      - sh ./scripts/npm-token.sh $NPM_TOKEN
    secrets: [ npm_token ]

  PUBLISH:
    image: node:8.10
    commands:
      - ID_RSA=$GITHUB_SSH_KEY
      - export ID_RSA
      - sh ./scripts/github-access.sh
      - sh ./scripts/npm-token.sh $NPM_TOKEN
      - sh ./scripts/publish.sh $DRONE_COMMIT_MESSAGE
    secrets: [ github_ssh_key, npm_token ]

    when:
      branch: [ master ]
      event: [ push ]

