pipeline:
  install:
    image: node:8.10
    commands:
      - npm install
    when:
      event:
        - push

  lint:
    image: node:8.10
    commands:
      - npm run lint
    when:
      event:
        - push

  test:
    image: node:8.10
    commands:
      - npm run test
    when:
      event:
        - push

