clone:
  CLONE REPO:
    image: plugins/git
    depth: 1

pipeline:
  TEST PULL REQUEST:
    image: node:8.10
    commands:
      - npm install
      - npm run lint
      - npm run test
      - npm run build
    when:
      event:
        - pull_request

  BUILD BRANCH:
    image: node:8.10
    commands:
      - npm install
      - npm run lint
      - npm run test
      - npm run build
    when:
      branch:
        - master
        - develop
      event:
        - push

  DEPLOY DEVELOPMENT:
    image: plugins/s3
    bucket: drone-ci-test
    region: eu-west-1
    access_key: [aws_access_key]
    secret_key: [aws_secret_key]
    source: dist/**/*
    target: drone-cli-test/target/dev
    strip_prefix: true
    when:
      event:
        - pull_request

  DEPLOY PRODUCTION:
    image: plugins/s3
    bucket: drone-ci-test
    region: eu-west-1
    access_key: [aws_access_key]
    secret_key: [aws_secret_key]
    source: dist/**/*
    target: drone-cli-test/target/prod
    when:
      branch:
        - master
      event:
        - push
