clone:
  CLONE_REPO:
    image: plugins/git
    depth: 1

pipeline:
  TEST_PULL_REQUEST:
    image: node:8.10
    commands:
      - npm install
      - npm run lint
      - npm run test
    when:
      event:
        - pull_request

  BUILD_BRANCH:
    image: node:8.10
    commands:
      - npm install
      - npm run lint
      - npm run test
      - npm run build
    when:
      branch:
        - master
        - develop
      event:
        - push
