clone:
  git:
    image: plugins/git
    depth: 1

pipeline:
  PullRequest:
    image: node:8.10
    commands:
      - npm install
      - npm run lint
      - npm run test
    when:
      event:
        - pull_request

  MergeBranch:
    image: node:8.10
    commands:
      - npm install
      - npm run lint
      - npm run test
      - npm run build
    when:
      branch:
        - master
        - develop
      event:
        - push
