clone:
  CLONE REPO:
    image: plugins/git
    depth: 1

pipeline:
  # INSTALL DEPENDENCIES:
  #   image: node:8.10
  #   commands:
  #     - npm install

  # LINT:
  #   image: node:8.10
  #   commands:
  #     - npm run lint

  # UNIT TEST:
  #   image: node:8.10
  #   commands:
  #     - npm run test

  # BUILD:
  #   image: node:8.10
  #   commands:
  #     - npm run build

  publish:
    image: node:8.10
    secrets: [github_token]
    when:
      event: push
      branch: master
    commands:
      - "git config --global url.https://${GITHUB_TOKEN}@github.com/.insteadOf ssh://git@github.com/"
      - git config user.email "builder@dazn.com"
      - git config user.name "CI"
      - git config --global push.default simple
      - npm version patch -m "[ci skip] Publish v%s"
      - git push origin master

  SSH GITHUB ACCESS:
    image: node:8.10
    environment:
      - ID_RSA=$GITHUB_SSH_KEY
    commands:
      - sh ./scripts/github-access.sh
      # - mkdir -p ~/.ssh
      # - touch ~/.ssh/known_hosts
      # - ssh-keyscan github.com >> ~/.ssh/known_hosts
      # - eval "$(ssh-agent -s)"
      # - echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
      # - echo $GITHUB_SSH_KEY > ~/.ssh/id_rsa
      # - chmod 600 ~/.ssh/id_rsa
      # - git config --global url.ssh://git@github.com/.insteadOf https://github.com/
      # - git config --global push.default simple
      # - git config --global user.email "juliantellezmendez@gmail.com"
      # - git config --global user.name "Julian Tellez"
      # - sh ./scripts/publish.sh $DRONE_COMMIT_MESSAGE
    secrets: [ github_ssh_key ]

  # PUBLISH:
  #   image: node:8.10
  #   environment:
  #     - ID_RSA=$GITHUB_SSH_KEY
  #   commands:
  #     - sh ./scripts/github-access.sh
  #     - sh ./scripts/publish.sh $DRONE_COMMIT_MESSAGE
  #   secrets: [ github_ssh_key ]

  #   when:
  #     branch: [ master ]
  #     event: [ push ]

